---
date: 2017-04-25T11:26:21+02:00
draft: false
title: use cash flows statement fafs0004au
---

**Remember:**
The cash flow statement, the investing activities section, is used to see the cash paid for purchases of property, plant and equipment. 

The depreciation, amortization and impairment expense can be usually seen in the cash flow statement, the operating activities section. The depreciation expense decreases the profit.

***

**Question**
Based on the financil statements of [AstraZeneca Plc](https://drive.google.com/file/d/0B5iOWuUx99FWaWVtSjVjWHR1TEU/view?usp=sharing), what is the cash amount paid to purchase Property, Plant and Equipment in 2015 and what is the effect of the depreciation, amortization and impairment expense on the operating income in 2015? 

1.	$1,446 million and an increase of $2,357 million

2.	$1,446 million and a decrease of $2,357 million

3.	$1,364 million and an increase of $492 million

4.	$1,364 million and a decrease of $482 million

***

**Solution:**
Point 2.
