---
date: 2017-06-10T17:29:05+02:00
draft: false
title: investments equity liabilities in financial statements fafs0005au
---

***

**Question**

Based on the financial statements of [Apple](goo.gl/mdJjXJ) identify:

1. How much cash dividend did Apple declare in 2015 ($11,627)

2. How much cash divided did Apple pay in 2015 ($11,561)

3. How much investments (accounted for under the equity method and the fair value method) does Apple have in 2015 (20,481+164,065)

4. How much long term debt did Apple issue in 2015? (27,114)

5. How many shares outstanding does Apple have in 2015? ($5,866,161)

6. How much treasury shares (in $) did Apple repurchase for cash in 2015? (35,253)

7. Did Apple borrow more or pay off more long-term debt during 2015? (proceeds from issues of debt are bigger than repayments so Apple borrowed more than it repaid in 2015) 

8. How much income is attributable to other parties that have an interest in Apple’s subsidiaries? (from these financial statements $0)

****

**Solution**

1. $11,627

2. $11,561

3. 20,481 + 164,065

4. 27,114

5. $5,866,161

6. 35,253

7. Proceeds from issues of debt are bigger than repayments so Apple borrowed more than it repaid in 2015

8. From these financial statements $0