---
date: 2017-07-01T10:17:47+02:00
draft: false
title: use financial statements fafs0007aan
---

**Remember:**

BIDE formula: Beginning balance + Increases - Decreases = Ending balance

***
  
**Question**

Use the information from [KPN](https://drive.google.com/file/d/0B5iOWuUx99FWLTZCNm1DVzBsbHM/view?usp=sharing) to:

1. Estimate the amount expected to be collected from KPN customers in 2017: a) 1,152 b) 12 c) 766 d) 778

2. Calculate the effect of depreciation expense on the total net cash flow in 2016. Ignore the tax impact: a) Decrease of 1,616 b) Decrease of 1,545 c) Increase of 1,545 d) No effect

3. Estimate the cost of purchased inventory in 2016. Assume inventory impairments of zero: a) 2,113 b) 18 c) 2,131 d) 2,149

4. Calculate the amount of dividends paid by KPN in 2016. The Statement of Changes in Equity is not available: a) 2,343 b) 487 c) 495 d) 110

***
  
**Solution:**

1. Definition accounts receivable: amounts expected to be collected from customers: answer c)

2. The depreciation expense has no effect on the net cash flow from operations because it is a non-cash expense. The depreciation expense is added to the net income to come to the net cash flow from operations but that does mean that the cash flow was lower or higher before adding the depreciation expense; answer d)

3. BIDE formula: Beginning balance inventory 65 + Purchases (?) - Cost of Goods Sold 2,131 = Ending balance inventory 47 ; ? = 47 + 2,131 - 65 = 2,113 ; answer a)

4. In the financing side of the cash flows statements: - 1,415 + 265 - 1,235 + 1,831 +67 = -487 
answer b)


