---
date: 2017-06-09T16:00:37+02:00
draft: false
title: trading securities fain0002aap
---

**Remember:**
A company that invests in the shares of other companies (i.e., an investor) can use three accounting methods to record these investments: (1) **fair value** method (for Treasury Shares [e.g., treasury shares can be short-term investments in other companies, usually in small percentages] and Available-for-Sales securities [e.g., available-for-sales securities can be long-term investments in other companies, usually in small percentages]); (2) **equity method** (for investments in associates [e.g., when the investor has between 25% and 50% of the shares of the investee]); (3) **consolidation method** (for subsidiaries [e.g., when the investor has over 50% of the shares of the investee]).

Changes in fair values only matter under the fair value method. Changes in the fair value of treasury shares create an **Unrealized Gain (or Loss)** that affects directly the income statement. Changes in the fair value of available-for-sales securities create an **Unrealized Gain (or Loss)** that is recorded directly in the "Accumulated Other Comprehensive Income OCI - Reserves" section of the Equity.

***

**Question:**

At the end of the first year of operations, Company E holds trading securities with a total fair value of \$1,150,000. The cost of the trading securities was \$1,100,000. The financial statements should show:

1. An unrealized gain of $50,000 in the Other Comprehensive Income section

2. An unrealized gain of $50,000 in the Income Statements section

3. An unrealized loss of $50,000 in the Other Comprehensive Income section

4. An unrealized loss of $50,000 in the Income Statement section 

***

**Solution:**
Point 2.