---
date: 2017-06-09T16:24:02+02:00
draft: false
title: equity method fain0004ar
---

**Remember:**

Under the equity method the investment account is affected by the proportional changes in the investee's net assets (net assets is that same as assets minus liabilities so net assets is another name for equity).

***

**Question:**

Which of the following statements is correct:

1. Under the equity method, the proportional share of profit from associates (accounted for under the equity method) is subtracted from the profit of the investor

2. Under the equity method, the proportional share of dividends from associates (accounted for under the equity method) increases the profit of the investor

3. Under the equity method, the proportional share of Other Comprehensive Income from associates is added to the Other Comprehensive Income of the investor

4. Under the equity method, the profit from associates is added to the investment carrying amount, irrespective of the percentage held by the investor in the investee


***

**Solution:**

1. Under the equity method, the proportional share of profit from associates (accounted for under the equity method) is subtracted from the profit of the investor

No. The proportional share of profits from associates should be added to the profit of the investor, not subtracted.

2. Under the equity method, the proportional share of dividends from associates (accounted for under the equity method) increases the profit of the investor

No. When the investor receives dividend under the equity method it increases the cash account and it decreases the investment account.

3. Under the equity method, the proportional share of Other Comprehensive Income from associates is added to the Other Comprehensive Income of the investor

Yes. The OCI of the investee is part of its net assets (or equity) and under the equity method any proportional changes in the net assets of the investee should be recorded by the investor in its investment account.

4. Under the equity method, the profit from associates is added to the investment carrying amount, irrespective of the percentage held by the investor in the investee

No. The percentage of interest matters under the equity method.
