---
date: 2017-07-03T12:05:40+02:00
draft: false
title: consolidation versus the equity method fain0008ee
---

**Remember**

Under the consolidated method and the equity method the net income is the same. Under the consolidated method the average assets are bigger than the average assets under the equity method.  

***

**Question **

Company A has a 49\% interest in Company B. Company B records in 2017 a net income of &euro;10 million. Company A is considering whether to use the consolidation method or the equity method to account for the investment in Company B. Which of the following statements is correct? Assume that the Net income is lower than average Assets and that in order to calculate Return-on-Assets only the Profit attributable to shareholders of Company A is considered.

a) Under the consolidation method (compared to the equity method), Company A will show a higher Return-on-Assets for 2017

b) Under the consolidation method (compared to the equity method), Company A will show the same Return-on-Assets for 2017

c) Under the consolidation method, the Return-on-Assets for Company A cannot be calculated

d) Under the consolidation method (compared to the equity method), Company A will show a lower Return-on-Assets for 2017

***

**Solution**

Under the consolidated method the net income is divided by a bigger amount than under the equity method so the return-on-assets is lower under the consolidated method than under the equity method.

Answer: d)