---
date: 2017-07-01T12:04:20+02:00
draft: false
title: capitalization versus expenses fai0010au
---

**Remember:**

The cost of inventory on the balance sheet represents all the costs that the entity incurres to make the inventory ready for sale (e.g., puchase cost, costs of bringing the inventories to their present location and condition). Storage of inventory is an expense and not an inventory cost.

***
  
  **Question**
Which of the following statements is correct about a dairy manufacturing company:

1. The cost of raw milk, storage costs of packaged cheese and cost of additives added to cheese are
inventory costs while the cost of the sales staff is an expense

2. The cost of raw milk, cost of transportation of raw milk to the dairy company from suppliers and
the labor cost of factory personnel are inventory costs while the storage costs of packaged cheese is
an expense

3. The cost of additives added to cheese, the depreciation of the factory building and the storage
costs of packaged cheese are inventory costs while the depreciation of the head office is an expense

4. The depreciation of the factory building, the labor cost of the human resources department and
the labor cost of the factory personnel are inventory costs while the storage costs of packaged
cheese is an expense

***
  
**Solution:**
Point 2.

