---
date: 2017-07-03T10:22:36+02:00
draft: false
title: equity calculation fae0004br
---

**Remember:**

Elements of equity: Share capital, Additional paid-in capital, Retained Earnings, Accumulated Other Comprehensive income, Treasury shares

***

The following items are collected from Sonic’s financial statements:

Financial statement item | Amount
------------------------ | -------
Accounts payable | &euro;500,000             
Share capital    | &euro;10,000
Additional paid-in capital | &euro;1,030,000 
Loans made through bonds | &euro;2,000,000
Unearned revenue | &euro;255,000             
Accumulated other comprehensive income | &euro;25,000
Retained earnings | &euro;750,000            
Provision for warranty repairs | &euro;150,000  
Investments in bonds | &euro;1,200,000       
Contingent liabilities | &euro;350,000

**Question:**

What it the total equity of Sonic?

a) &euro;1,805,000

b) &euro;1,815,000

c) &euro;3,015,000

d) &euro;3,815,000

***

**Solution:**

Additional paid-in capital + Retained Earnings + Share capital + Accumulated other comprehensive income

Answer: b)