---
date: 2017-07-01T09:49:16+02:00
draft: true
title: use financial statement information fafs0006bap
---

**Remember:**
How financial statements are linked: [FinancialStatements](https://drive.google.com/file/d/0B5iOWuUx99FWWnZRWUhiX1JuczA/view?usp=sharing) 

***
  
**Question**

Use the information from [Ahold](https://drive.google.com/file/d/0B5iOWuUx99FWZ1FiMGd4QVVsTTA/view?usp=sharing) to:

1. Calculate the 2016 net income: a) 13,378 b) 2,982 c) 1,518 d) 1,089

2. Calculate the 2016 ending balance of equity: a) 7,211 b) 7,140 c) 6,711 d) 8,069

3. Calculate the 2016 total net cash from operating, investing and financing activities: a) 4,195 b) 1,591 c) 1,162 d) 3,766

4. Calculate the 2016 total current assets: a) 4,876 b) 7,864 c) 5,114 d) 6,702

5. Calculate the 2016 total assets: a) 31,019 b) 31,681 c) 30,592 d) 32,181

***
  
**Solution:**

1. Net sales 49,695 - Cost of sales 36,317 - Selling expenses 9,876 - Interest expenses 273 - Depreciation expenses 1,464 - Income tax expenses 247 = 1,518 ; answer c)

2. Equity	5,622 + Net income	1,518 + OCI	500 - dividends 429 = 7,211 ; answer a)

(if there is no additional information then the dividends paid are equal to dividends declared)

3. Net cash operating	2,893 - Net cash investing 1,302 - Net cash financing 429 = 1,162 ; answer c)

4. Inventories 3,288 + Receivables 1,588 + Cash	2,988 (from beginning balance 1,826 + net change in cash 1,162) = 7,864 ; answer b)

5. PPE 11,770 + Intangible assets	12,547 + Inventories 3,288 + Receivables 1,588 + Cash	2,988 = 32,181 ; answer d)


