---
date: 2017-06-09T16:08:51+02:00
draft: false
title: fair value and equity method fain0003ean
---

**Remember:**
A company that invests in the shares of other companies (i.e., an investor) can use three accounting methods to record these investments: (1) **fair value** method (for Treasury Shares [e.g., treasury shares can be short-term investments in other companies, usually in small percentages] and Available-for-Sales securities [e.g., available-for-sales securities can be long-term investments in other companies, usually in small percentages]); (2) **equity method** (for investments in associates [e.g., when the investor has between 25% and 50% of the shares of the investee]); (3) **consolidation method** (for subsidiaries [e.g., when the investor has over 50% of the shares of the investee]).

Changes in fair values only matter under the fair value method. Changes in the fair value of treasury shares create an **Unrealized Gain (or Loss)** that affects directly the income statement. Changes in the fair value of available-for-sales securities create an **Unrealized Gain (or Loss)** that is recorded directly in the "Accumulated Other Comprehensive Income OCI - Reserves" section of the Equity.

Under the equity method the investment account is affected by the proportional changes in the investee's net assets (net assets is that same as assets minus liabilities so net assets is another name for equity).

***

**Question:**

A company holds the following investments in other companies: long-term investments (available-for-sale) accounted for at fair value, trading securities accounted for at fair value and investments in associates accounted for under the equity method. During the period the following occurs: the trading securities are sold for cash at a gain, the share price (fair market value) of both the long-term investments (available-for-sale) and that of the investments in associates increases and there is a payment of dividend by the investments held in associates. Which of the following is correct:

1. The income statement contains an “Unrealized Gain from Investments”

2. The cash flows statement – financing activities contains “Proceeds from trading securities”

3. The equity contains OCI from “Unrealized Gain from Investments”

4. The income statements contains a dividend income

***

**Solution:**

1. The income statement contains an “Unrealized Gain from Investments”

No. The income statement would contain an "Unrealized Gain" only if the fair value of the trading security would have increased.

2. The cash flows statement – financing activities contains “Proceeds from trading securities”

No. There is cash received from the sale of trading securities but this cash will be placed under the investing activities in the cash flow statement.

3. The equity contains OCI from “Unrealized Gain from Investments”

Yes. The increase in the fair value of the available for sale securities will be recorded as an "Unrealized Gain" in the OCI (not the income statement).

4. The income statements contains a dividend income

No. When dividend is received from investments accounted for under the equity method the cash increases and the investment account decreases.
