---
date: 2017-06-09T12:48:22+02:00
draft: false
title: available for sales fair value fain0001ar
---

**Remember:**
A company that invests in the shares of other companies (i.e., an investor) can use three accounting methods to record these investments: (1) **fair value** method (for Treasury Shares [e.g., treasury shares can be short-term investments in other companies, usually in small percentages] and Available-for-Sales securities [e.g., available-for-sales securities can be long-term investments in other companies, usually in small percentages]); (2) **equity method** (for investments in associates [e.g., when the investor has between 25% and 50% of the shares of the investee]); (3) **consolidation method** (for subsidiaries [e.g., when the investor has over 50% of the shares of the investee]).

Changes in fair values only matter under the fair value method. Changes in the fair value of treasury shares create an **Unrealized Gain (or Loss)** that affects directly the income statement. Changes in the fair value of available-for-sales securities create an **Unrealized Gain (or Loss)** that is recorded directly in the "Accumulated Other Comprehensive Income OCI - Reserves" section of the Equity.

Under the equity method the investment account is affected by the proportional changes in the investee's net assets (net assets is that same as assets minus liabilites so net assets is another name for equity).

***

**Question:**
Available-for-sale investments are accounted for at:
1. Fair value; with changes in fair values through the income statement (OCI)
2. Fair value; with changes in fair values through other comprehensive income
3. Amortized cost 
4. Cost with adjustments for post-acquisition changes in the investor’s share of net assets of the investee


***

**Solution:**
Point 2.