---
date: 2017-04-24T19:26:27+02:00
draft: false
title: depreciation gain cash fafs0001es
---

```{r echo=FALSE, error=FALSE, results='hide'}
patent <- 10730 
building <- 90188 
amortization <- 668 
depreciation <- 4564
cost <- 55110
acc_depr <- 26509
gain <- 9518
cash_op <- depreciation + amortization - gain
cash_op
year <- 2015
cash_inv <- (-patent - building) + (gain + (cost - acc_depr))
cash_inv
```


**Remember:**
Cash (proceeds) from sale of property, plant and equipment = Value of the asset (net of amortization or depreciation) +/- Gain/Loss on sale. 

In the indirect method of building the cash flow statement, the non-cash expenses (e.g., depreciation expense) or gains are added to the net profit to find the cash from operating activities.

Cash flow from investing activities relates to the purchase and sale of property, plant and equipment and intangible assets.

***

During `r year` Castro Company buys patents for $`r format(patent, big.mark=",")` (paid in cash) and a building for $`r format(building, big.mark=",")` (paid in cash). During `r year` the amortization expense of patents was $`r format(amortization, big.mark=",")` and the depreciation expense of the building was $`r format(depreciation, big.mark=",")`. Also during `r year` equipment with an initial cost of $`r format(cost, big.mark=",")` and an accumulated depreciation of $`r format(acc_depr, big.mark=",")` was sold for a gain of $`r format(gain, big.mark=",")` (cash transaction). Assume a net profit of zero. 

**Question:**
What would be the net cash flow from operating activities (through the indirect method)? 

***

**Solution:** $`r format(cash_op, big.mark=",")`

***

**Question:**
What would be the net cash flow from investing activities?

***

**Solution:** $`r format(cash_inv, big.mark=",")`
